### PR TITLE
feat: expose firmware version

### PR DESCRIPTION
**Pull request by CFenner**
Will this be enough to expose the firmware version?

### CODE REVIEW

**Comment by hellqvio86** [comment]
Yes, it should be enough if firmware version is present in the websocket messages, do you see them here? :slightly_smiling_face: 

Easiest is probably grepping after this debug message in the log:
`LOGGER.debug(f"process_unit_event - Processing msg: {pformat(msg)}")`

**Comment by CFenner** [comment]
```
2022-11-25 13:30:58.734 DEBUG (MainThread) [aiocasambi.units] processing_unit_event - key: vVxAG9CjHHVFcI2xAd2omKmyGVZQ7doW-1 name: CURVED Mitte msg: {'address': 'x', 'controls': [{'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0}, {'name': 'dimmer1', 'type': 'Dimmer', 'value': 0.0}, {'min': 2200, 'max': 5000, 'level': 0.18214285714285713, 'name': 'temperature', 'type': 'CCT', 'value': 2710.0}], 'method': 'unitChanged', 'fixtureId': 22133, 'condition': 0.0, 'wire': 20, 'activeSceneId': 0, 'sensors': {}, 'name': 'CURVED Mitte', 'online': False, 'id': 1, 'dimLevel': 0.0, 'status': 'ok'} method unit changed control value: 0.0
```

Looks like it's not the case, but it's part of the `get_network_state`:

```
2022-11-25 13:29:52.147 DEBUG (MainThread) [aiocasambi.controller] get_network_state response: {'activeScenes': [], 'id': 'x', 'revision': 36, 'grade': 'EVOLUTION', 'address': 'x', 'name': 'BV47', 'type': 'CLOSED', 'timezone': 'Europe/Berlin', 'gateway': {'name': 'Christophers iPhone'}, 'units': {'1': {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'activeSceneId': 0, 'id': 1, 'address': 'x', 'name': 'CURVED Mitte', 'firmwareVersion': '36.30', 'position': 2, 'fixtureId': 22133, 'groupId': 0, 'type': 'Luminaire'}, '2': {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'activeSceneId': 0, 'id': 2, 'address': 'x', 'name': 'CURVED Rechts', 'firmwareVersion': '36.30', 'position': 3, 'fixtureId': 22133, 'groupId': 0, 'type': 'Luminaire'}, '3': {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'activeSceneId': 0, 'id': 3, 'address': 'x', 'name': 'CURVED Links', 'firmwareVersion': '36.30', 'position': 1, 'fixtureId': 22133, 'groupId': 0, 'type': 'Luminaire'}}, 'photos': [], 'scenes': {}, 'groups': {}}
```

Does that help?

**Comment by hellqvio86** [comment]
It needs to be handled in **process_network_state** for units then

**Comment by hellqvio86** [comment]
Its implemented now in aiocasambi *0.256* and its set in the initialization phase

**Pull request closed without merging**
